== Projekt 2 Úloha 6 - Přepis znaků z klávesnice na zobrazovač
=== Zadání
==== 1. část - klávesnice
Předpokládejte, že k rozhraní PS/2 desky je připojena běžná PC klávesnice. Přijímejte znaky z klávesnice a převádějte je do ASCII kódu. Musíte podporovat zejména tyto klávesy:

Klávesy s písmeny - produkují ASCII kódy velkých písmen.

Klávesy s číslicemi - produkují ASCII kódy číslic (ASCII kódy 0x30-0x39).

Klávesa Enter - produkuje znak LF (ASCII kód 0x0A).

Mezerník - produkuje znak mezera (ASCII kód 0x20).

Ostatní klávesy a události puštění klávesy korektně ignorujte. Protokol PS/2 a důležité kódy kláves jsou v dokumentaci desky. Tam jsou také odkazy na podrobnější specifikace.

==== 2. část - zobrazovač
Znaky, které přicházejí z 1. části, zobrazujte na sedmisegmentovém displeji klasicky, tj. zleva doprava.

Pokud jsou zaplněné všechny 4 pozice, pak při přijetí nového znaku posuňte text doleva o 1 pozici.

Klávesa Enter "odřádkuje", tj. diplej zhasne a budeme zadávat znaky opět od nejlevější pozice.

Pro zobrazení písmen můžete využít znaky definované např. v https://en.wikipedia.org/wiki/Seven-segment_display. Pro znaky, které se v sadě nevyskytují (např. K, M), nadefinujte vlastní tvary.

Můžete (ale nemusíte) implementovat kurzor - blikající podtržítko.

=== Implementační platforma

Úloha byla realizována na FPGA přípravku Digilent Basys 3

=== Popis chování

Momentálně je v projektu pouze testbench pro softwarový model PS2 entity která přijímá signály z klávesnice, a softwarovy model samotný. Chování přenosu dat jsem navrhoval podle specifikace na stránce http://www.burtonsys.com/ps2_chapweske.htm

SW model by měl implementačně sedět se specifikací kromě neimplementování host to device komunikace. 

U TB je rozdíl v tom, že ve specifikaci je uvedena 10-14khz hodinová PS2 frekvence a já si zvolil o několik řádů vyšší frekvenci. Měl jsem problémy se simulací protože to simulačně trvá velmi dlouho, pro 256 vstupů a pomalý PS2 clk naproti 50Mhz vnitřnímu clk. Na funkcionalitu by to však nemělo mít vliv.

Simulační soubor obsahuje 256 řádků vygenerovaných vstupů a výstupů, aby se všechny vykonaly musí být nastavený dostatečně dlouhý simulační čas. V souboru s testbenchem se musí nastavit cesta k souboru ps2input.txt proměnné SIMDATA aby testbench fungoval. 

Dále je v simulačním souboru na posledním řádku chyba, to je proto aby se zkontrolovalo že simulace určitě porovnává vstupy a výstupy.

V implementaci je také resetovací tlačítko, které je vyvedeno na BTND.

=== Popis souborů

Složka PS2Gen obsahuje jednoduchý C program na generování vstupů a výstupů pro simulaci

[options="autowidth"]
|====
^h|  Soubor               ^h|  Popis
| SW_KEYBOARD.vhd           | Softwarový model entity klávesnice
| TB_KEYBOARD.vhd           | Test-bench pro entitu klávesnice
| ps2input.txt              | Testovací data pro test-bench klávesnice
| DISPLAY.vhd               | Komponenta která zpracovává ascii znaky z komponenty klávesnice a zobrazuje je na display. Celkem uchovává 4 znaky.
| DD_SYNC.vhd               | Komponenta která synchronizuje asynchronní vstup signálů z fyzické klávesnice. 2x D klopný obvod
| KEYBOARD_UNIT.vhd         | Komponenta která spojuje řadič a datovou část klávesnice
| KEYBOARD_DP.vhd           | Datová část klávesnice
| KEYBOARD_CONTROLLER.vhd   | Řadič klávesnice
| TB_KeyToDisp.vhd          | Jednoduchý testbench pro celý projekt. Pouze posílá signály abychom se mohli podívat jak na ně naše implementace reaguje v simulaci
| key2seg_constr.xdc        | Soubor s pinovým přiřazením
| scanInput.txt             | Soubor s testovacími daty pro TB_KeyToDisp
|====
