# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.cache/wt [current_project]
set_property parent.project_path C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/new/DD_SYNC.vhd
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/new/DISPLAY.vhd
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/new/KEYBOARD_CONTROLLER.vhd
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/new/KEYBOARD_DP.vhd
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/new/KEYBOARD_UNIT.vhd
  C:/Users/marti/OneDrive/CVUT/Semester5/PNO/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/sources_1/imports/Documents/Key2LED.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/constrs_1/new/key2seg_constr.xdc
set_property used_in_implementation false [get_files C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.srcs/constrs_1/new/key2seg_constr.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Key2SegDisp -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Key2SegDisp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Key2SegDisp_utilization_synth.rpt -pb Key2SegDisp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
