webtalk_init -webtalk_dir C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.sim/sim_1/behav/xsim/xsim.dir/TB_DISPLAY_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 30 00:13:33 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2bac70232fde53b585488a088e5d81f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d407afbe4f33497c9ae1cb18000dbfb5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2032065687 -regid "" -xml C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.sim/sim_1/behav/xsim/xsim.dir/TB_DISPLAY_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.sim/sim_1/behav/xsim/xsim.dir/TB_DISPLAY_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/marti/OneDrive/CVUT/Semester5/PNO/GITLAB/Semestralka2_KeyboardToDisplay/Key2Disp/Key2Disp.sim/sim_1/behav/xsim/xsim.dir/TB_DISPLAY_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
